# -*- coding: utf-8 -*-
"""WPS_MVP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5Xim3h24dqBBr2Iv1C0MVALGEsRNGRw
"""

# Commented out IPython magic to ensure Python compatibility.
# !pip install streamlit pandas numpy
# 
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# 
# # -----------------------------------
# # PAGE CONFIG (Professional UI)
# # -----------------------------------
# st.set_page_config(page_title="WPS Disaster Prioritization", layout="wide")
# 
# # -----------------------------------
# # TITLE
# # -----------------------------------
# st.title("Weighted Priority Scheduler (WPS)")
# st.subheader("Disaster Response Prioritization System")
# 
# st.write("""
# This system applies the Weighted Sum Model (WSM) with an equal weighting scheme
# to prioritize disaster-affected areas based on impact criteria.
# """)
# 
# # -----------------------------------
# # FILE UPLOAD (More professional)
# # -----------------------------------
# st.header("Upload Disaster Data")
# 
# uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])
# 
# # -----------------------------------
# # SAMPLE DATA OPTION
# # -----------------------------------
# if uploaded_file is None:
#     st.info("Using sample data. Upload a CSV to use your own dataset.")
# 
#     data = {
#         "Barangay": ["A", "B", "C"],
#         "Casualties": [5, 2, 8],
#         "Affected_Families": [100, 150, 80],
#         "Damaged_Houses": [20, 10, 30]
#     }
#     df = pd.DataFrame(data)
# else:
#     df = pd.read_csv(uploaded_file)
# 
# # -----------------------------------
# # DISPLAY DATA
# # -----------------------------------
# st.subheader("Input Data")
# st.dataframe(df)
# 
# # -----------------------------------
# # NORMALIZATION FUNCTION
# # -----------------------------------
# def normalize(column):
#     if column.max() == column.min():
#         return column * 0
#     return (column - column.min()) / (column.max() - column.min())
# 
# # -----------------------------------
# # APPLY NORMALIZATION
# # -----------------------------------
# df["Norm_Casualties"] = normalize(df["Casualties"])
# df["Norm_Affected"] = normalize(df["Affected_Families"])
# df["Norm_Damaged"] = normalize(df["Damaged_Houses"])
# 
# # -----------------------------------
# # EQUAL WEIGHTING (WSM)
# # -----------------------------------
# weight = 1 / 3
# 
# df["Priority Score"] = (
#     df["Norm_Casualties"] * weight +
#     df["Norm_Affected"] * weight +
#     df["Norm_Damaged"] * weight
# )
# 
# # -----------------------------------
# # PRIORITY SCHEDULING (SORTING)
# # -----------------------------------
# df_sorted = df.sort_values(by="Priority Score", ascending=False)
# 
# # -----------------------------------
# # RESULTS
# # -----------------------------------
# st.subheader("Prioritized Results")
# st.dataframe(df_sorted)
# 
# # -----------------------------------
# # VISUALIZATION
# # -----------------------------------
# st.subheader("Priority Score Visualization")
# st.bar_chart(df_sorted.set_index("Barangay")["Priority Score"])
# 
#

"""%%writefile requirements.txt
streamlit
pandas
numpy
"""